### ISSUE TITLE
Visualization of target trajectory

### ISSUE THREAD

**Issue by juhe9842** [Digital-Humans-23/a1#10]
Do we need to care about the visualization of the target trajectory when implementing the offset on the target position for Ex.4? For example on my side the robot follow the terrains but the visualized base and feet trajectories are still on the flat ground

**Comment by juhe9842** [comment]
sorry for Ex.5

**Comment by juhe9842** [comment]
Another question is how should we handle the base positions on discontinuous terrain like stages and stairs? There is a sudden change of base height on such terrains if we only give it an offset.

**Comment by eastskykang** [comment]
Good question. In short, you don't have to modify trajectories. You just can add offsets to IK targets as I mentioned. 

Of course, the base and feet height will change abruptly on discontinuous height map (such as staircases), but generating trajectories for such terrain itself is an active research topic. So, you won't lose a point due to this problem. 

But, if you can improvise a strategy to generate smooth trajectories, you are more than welcome to implement it :)
